steps:
  - name: maven:3.6.3-jdk-11-openj9
    entrypoint: mvn
    args: ['package', '-Pnative', '-Dquarkus.native.container-build=true']
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-f', 'src/main/docker/Dockerfile.distroless', '-t', 'binxly/constructor', '.']

