steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-f', 'src/main/docker/Dockerfile.distroless', '-t', 'gcr.io/$PROJECT_ID/binxly-constructor:$COMMIT_SHA', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'push', 'gcr.io/$PROJECT_ID/binxly-constructor:$COMMIT_SHA' ]
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
     - 'run'
     - 'deploy'
     - 'binxly-constructor'
     - '--image'
     - 'gcr.io/$PROJECT_ID/binxly-constructor:$COMMIT_SHA'
     - '--region'
     - 'REGION'
     - '--platform'
     - 'managed'
images: ['gcr.io/$PROJECT_ID/binxly-constructor:$COMMIT_SHA']
